# Lab 3

## Reading `NumPy` Arrays

In [ ]:
import numpy as np
X = np.genfromtxt("ionosphere.txt", delimiter=",")
X[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ,  1.     ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447, -1.     ],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644

In [2]:
len(X[0])

35

In [7]:
X = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=np.arange(34))
print(X[:3])

y = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=34, dtype='int')
print(y[:3])

[[ 1.       0.       0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708
   1.       0.0376   0.85243 -0.17755  0.59755 -0.44945  0.60536 -0.38223
   0.84356 -0.38542  0.58212 -0.32192  0.56971 -0.29674  0.36946 -0.47357
   0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.3409   0.42267 -0.54487
   0.18641 -0.453  ]
 [ 1.       0.       1.      -0.18829  0.93035 -0.36156 -0.10868 -0.93597
   1.      -0.04549  0.50874 -0.67743  0.34432 -0.69707 -0.51685 -0.97515
   0.05499 -0.62237  0.33109 -1.      -0.13151 -0.453   -0.18056 -0.35734
  -0.20332 -0.26569 -0.20468 -0.18401 -0.1904  -0.11593 -0.16626 -0.06288
  -0.13738 -0.02447]
 [ 1.       0.       1.      -0.03365  1.       0.00485  1.      -0.12062
   0.88965  0.01198  0.73082  0.05346  0.85443  0.00827  0.54591  0.00299
   0.83775 -0.13644  0.75535 -0.0854   0.70887 -0.27502  0.43385 -0.12062
   0.57528 -0.4022   0.58984 -0.22145  0.431   -0.17365  0.60436 -0.2418
   0.56045 -0.38238]]
[ 1 -1  1]


In [8]:
my_array = np.concatenate((np.arange(1000), np.array([4])))
print(my_array)

[  0   1   2 ... 998 999   4]


In [29]:
import time
def computeEuclideanNorm(vector: np.array) -> float:
    """Computes the Euclidean norm of a vector by summing the squares of each entry then square rooting"""

    sum = 0
    for i in range(0,vector.size):
        sum += np.power(vector[i], 2)
    
    return np.sqrt(sum)

x = np.array([4,3,4,5,2,5,6,6,3,2])
start = time.time()
print(computeEuclideanNorm(x))
print(time.time() - start,"seconds")

13.416407864998739
7.963180541992188e-05 seconds


In [28]:
import math
def computeMinimum(a: np.array):
    """Calculates the minimum value of an array"""

    current_min = math.inf
    for n in range(a.size):
        if current_min > a[n]:
            current_min = a[n]
    
    return current_min

start = time.time()
print(computeMinimum(x))
print(time.time() - start,"seconds")

2
0.0002155303955078125 seconds
